propagation_model:
  detection_threshold: -85.0
  noise_std: 4.0
  path_loss_exponent: 2.5
tags:
- altitude: 1.5
  latitude: 47.39843069045665
  longitude: 8.546549659921777
  tag_id: TAG_001
  tx_power: -45.0
- altitude: 1.5
  latitude: 47.39780672894279
  longitude: 8.54564233298139
  tag_id: TAG_002
  tx_power: -45.0
- altitude: 1.5
  latitude: 47.39783134300262
  longitude: 8.546308560874905
  tag_id: TAG_003
  tx_power: -45.0
- altitude: 1.5
  latitude: 47.39735428902474
  longitude: 8.546852687453468
  tag_id: TAG_004
  tx_power: -45.0
- altitude: 1.5
  latitude: 47.39808061582779
  longitude: 8.546065572040945
  tag_id: TAG_005
  tx_power: -45.0
- altitude: 1.5
  latitude: 47.39778687003553
  longitude: 8.547297325816977
  tag_id: TAG_006
  tx_power: -45.0
- altitude: 1.5
  latitude: 47.39798207124867
  longitude: 8.546144419237843
  tag_id: TAG_007
  tx_power: -45.0
- altitude: 1.5
  latitude: 47.39748812628563
  longitude: 8.545855028905466
  tag_id: TAG_008
  tx_power: -45.0
- altitude: 1.5
  latitude: 47.398299739465735
  longitude: 8.545667769175484
  tag_id: TAG_009
  tx_power: -45.0
- altitude: 1.5
  latitude: 47.397891000178234
  longitude: 8.546017781586746
  tag_id: TAG_010
  tx_power: -45.0
